
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'instruccionesBOOL BOOLEANO CMULTILINEAAPERTURA CMULTILINEACIERRE COMENTARIO COMENTARIOMULTI CUNALINEA DBL DECIMAL ENTERO ID IGUAL INT PTCOMA STR TEXTOinstrucciones : instruccion instrucciones\n                     | instruccioninstruccion : comentario_una_linea\n                   | comentario_multi_lineacomentario_una_linea : CUNALINEA COMENTARIOcomentario_multi_linea : CMULTILINEAAPERTURA COMENTARIOMULTI CMULTILINEACIERRE'
    
_lr_action_items = {'CUNALINEA':([0,2,3,4,8,10,],[5,5,-3,-4,-5,-6,]),'CMULTILINEAAPERTURA':([0,2,3,4,8,10,],[6,6,-3,-4,-5,-6,]),'$end':([1,2,3,4,7,8,10,],[0,-2,-3,-4,-1,-5,-6,]),'COMENTARIO':([5,],[8,]),'COMENTARIOMULTI':([6,],[9,]),'CMULTILINEACIERRE':([9,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'instrucciones':([0,2,],[1,7,]),'instruccion':([0,2,],[2,2,]),'comentario_una_linea':([0,2,],[3,3,]),'comentario_multi_linea':([0,2,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> instrucciones","S'",1,None,None,None),
  ('instrucciones -> instruccion instrucciones','instrucciones',2,'p_instrucciones','parser.py',7),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones','parser.py',8),
  ('instruccion -> comentario_una_linea','instruccion',1,'p_instruccion','parser.py',12),
  ('instruccion -> comentario_multi_linea','instruccion',1,'p_instruccion','parser.py',13),
  ('comentario_una_linea -> CUNALINEA COMENTARIO','comentario_una_linea',2,'p_comentario_una_linea','parser.py',17),
  ('comentario_multi_linea -> CMULTILINEAAPERTURA COMENTARIOMULTI CMULTILINEACIERRE','comentario_multi_linea',3,'p_comentario_multi_linea','parser.py',22),
]
